import AuthBtn from '../Components/NaviagationBar/AuthBtns'
import NavigationBar from '../Components/NaviagationBar/NavigationBar'
import TitleBtn from '../Components/NaviagationBar/TitleBtn'
import '../globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en" data-theme='dark'>
      <body>
      <NavigationBar >
        <TitleBtn />
        <AuthBtn/>
      </NavigationBar>
        {children}
      </body>
    </html>
  )
}

